name: Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: x86_64-apple-darwin
            os: macos-latest

          - target: aarch64-apple-darwin
            os: macos-latest

          - target: x86_64-pc-windows-gnu
            os: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.job.target }}

      - name: Setup Rust
        run: |
          rustup update
          rustup target add ${{ matrix.job.target }}

      - name: Cargo fmt
        run: |
          cargo fmt --all -- --check

      - name: Cargo test
        run: |
          cargo test --target ${{ matrix.job.target }}

      - name: Cargo run --example
        run: |
          cargo run --example basic --target ${{ matrix.job.target }}
